### ISSUE TITLE
SurveySimulator/python does not contain SurveySubs.f

### ISSUE THREAD

**Issue by rcdorsey** [OSSOS/SurveySimulator#11]
The current readme states that the file SurveySubs.f is contained within the python directory, which is incorrect.

Also, if symbolic links are to be used to link SurveySubs.f to the python directory, this should be included in the readme.

**Comment by ijiraq** [comment]
There is no need for ’symbolic links’ to various directories anymore, but I think the README needs some updating.  Thanks for pointing out the problems with the readme. I will correct.

JJ


On Oct 13, 2020, at 5:51 PM, rcdorsey <notifications@github.com<mailto:notifications@github.com>> wrote:



The current readme states that the file SurveySubs.f is contained within the python directory, which is incorrect.

Also, if symbolic links are to be used to link SurveySubs.f to the python directory, this should be included in the readme.

**Comment by rcdorsey** [comment]
Does that mean that SurveySubs.f should be in this folder? When I try to run Driver.py it can't find it to compile SurveySubs.

**Comment by ijiraq** [comment]
Hi,

I need to fix the package itself.

The way that the python directory is setup you would copy the SurveySubs.f into that directory to follow the README.python instructions. That’s fine.

We are, however, restructuring the source code and distribution so that the python module builds correctly.  I hope I can have that work done by the end of the week.

JJ


On Oct 14, 2020, at 8:02 PM, rcdorsey <notifications@github.com<mailto:notifications@github.com>> wrote:



Does that mean that SurveySubs.f should be in this folder? When I try to run Driver.py it can't find it to compile SurveySubs.

**Comment by rcdorsey** [comment]
Ah okay thank you, I will wait for the restructure to try again then.

**Comment by ijiraq** [comment]
The distribution has been significantly updated/restructured to the correct distribution.
