### ISSUE TITLE
The value of pos_b maybe used before being set

### ISSUE THREAD

**Issue by ijiraq** [OSSOS/SurveySimulator#16]
https://github.com/OSSOS/SurveySimulator/blob/master/fortran/F95/xvutils.f95#L244

Perhaps set value to 0 as init?

@jmpetit

**Comment by jmpetit** [comment]
Hi JJ,
the point is that you've moved the use of pos_b out of the IF block, and it is defined only in one of the branches. Now, the use of it is to determine the distance of the observatory to the Sun. So what to do depends on the origin of the position of the spacecraft in the first branch. We must decide it's always with respect the the Solar System barycenter. This is the case in your HTS file, coming from JPL. That's the natural output from DE441.
In this case, that's fine because in the ground observatory branch, I also compute the position of the observatory with respect to the Solar System barycenter. So we just have to move the call to BaryXV outside of the IF block, either before or right after, and then compute r.
DONE, commited. I'll close the issue.
JM
