### ISSUE TITLE
The lightcurve values are all zeros

### ISSUE THREAD

**Issue by ijiraq** [OSSOS/SurveySimulator#3]
We don't understand lightcurves.   Let's leave that out but fix later.

**Comment by Mikea1985** [comment]
Don't set the period to zero, that's obviously bad! ;-)

**Comment by ijiraq** [comment]
I think the value is set to ‘0’ as a special value.  But perhaps a negative value would be better, and that would indicate that no period is known.   Personally I don’t like ‘magic values’ and would prefer to use ‘NaN’ for unknown values, but I don’t know how to do that in Fortran.

JJ


On Feb 18, 2020, at 7:38 AM, Mike Alexandersen <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't set the period to zero, that's obviously bad! ;-)

**Comment by jmpetit** [comment]
Hi there,

indeed, never set the period to 0, since the program divides by period. That's something that is done in GiMeObj. My versions of GiMeObj don't set period to 0. Clearly we should decide on a convention and stick to it. And more importantly, I should modify Detos1 so it checks the value of period and avoids dividing by 0. That's an action item for me. The correct way to not have a lightcurve is to set amp to 0.

Cheers, Jean-Marc

**Comment by jmpetit** [comment]
Hi there,

I've pushed a new version of SurveySubs.f (and f95) to make sure that lightcurve is applied only when amp > 0 and period > 0. I think this is in master branch. Please merge if working in another branch.

Cheers, Jean-Marc

**Comment by jmpetit** [comment]
As explained above, this issue was fixed and can now be closed.
